<a href="https://colab.research.google.com/github/akshitagarwal11/CAFEBILL/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#IN this notebook , we are going to cover some of the most of the fundamental concepts of tensors using Tensorflow


##introduction to tensors


In [7]:
# Import TensorFlow
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.11/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [8]:
#create tensors with tf.constant()
scalar = tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [9]:
# check the no of dimensions
scalar.ndim

0

In [10]:
# create a vector
vector = tf.constant([12,12])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([12, 12], dtype=int32)>

In [13]:
# create a matrix
matrix = tf.constant([[12,2],
                     [4,4]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  2],
       [ 4,  4]], dtype=int32)>

In [18]:
another_matrix.ndim

2

In [27]:
tensor = tf.constant([[[1,2,3,],
 [4,5,6,]],
  [[7,8,9,],
   [1,1,1,]]])
tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 1, 1]]], dtype=int32)>

In [28]:
tensor.ndim

3